version: "3"

services:

  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=kavkevpassword
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    


  app:
    container_name: kavkev_app
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - app
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./static/:/static

  redis:
      image: redis

  celery:
    build:
      context: .
    container_name: celery-worker
    restart: always
    command: sh -c "celery -A ./kavKev_Site worker -l INFO"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - app
      - postgresdb

  celery-beat:
    build:
      context: .
    image: celery 
    container_name: celery-beat
    restart: always
    command: celery -A ./kavKev_Site beat -l INFO
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis 
      - celery
      - app
      - postgresdb

  

# volumes:
#   pgdata:
