version: "3"


services:

  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=kavkevpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: kavkev_app
    build:
      context: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
    depends_on:
      - postgresdb
      - web




  redis:
      image: redis

  celery:
    build:
      context: .
    container_name: celery-worker
    restart: always
    command: sh -c "celery -A ./kavKev_Site worker -l INFO"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - web
      - postgresdb

  celery-beat:
    build:
      context: .
    image: celery 
    container_name: celery-beat
    restart: always
    command: celery -A ./kavKev_Site beat -l INFO
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis 
      - celery
      - web
      - postgresdb

volumes:
  pgdata:
