version: "3"

services:

  db:
    container_name: kavkev_db
    image: postgres:10
    environment:
      POSTGRES_DB: "kavkevdb"
      POSTGRES_USER: "kavkevadmin"
      POSTGRES_PASSWORD: "kavkevpassword"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db


  redis:
      image: redis

  celery:
    build:
      context: .
    container_name: celery-worker
    restart: always
    command: sh -c "celery -A kavKev_Site worker -l INFO"
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
      - db

  celery-beat:
    build:
      context: .
    image: celery 
    container_name: celery-beat
    restart: always
    command: celery -A kavKev_Site beat -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis 
      - celery
      - app
      - db
volumes:
  pgdata:
