# Generated by Django 3.2.7 on 2021-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qt_quantity',
            new_name='qr_quantity',
        ),
        migrations.AddField(
            model_name='user',
            name='which_contest',
            field=models.CharField(choices=[('LESS_5', 'Less 5'), ('MORE_5_LESS_10', 'More 5 Less 10'), ('MORE_10_LESS_100', 'More 10 Less 100'), ('MORE_100', 'More 100')], default='LESS_5', max_length=50),
        ),
    ]
